//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDersleri_4.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsoleDbProjeEntities1 : DbContext
    {
        public ConsoleDbProjeEntities1()
            : base("name=ConsoleDbProjeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCurrency> TblCurrency { get; set; }
        public virtual DbSet<TblCurrencyValue> TblCurrencyValue { get; set; }
        public virtual DbSet<TblOperation> TblOperation { get; set; }
    }
}
