//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDersleri_4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCurrencyValue
    {
        public int ID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<decimal> CurrencyBuying { get; set; }
        public Nullable<decimal> CurrencySelling { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual TblCurrency TblCurrency { get; set; }
    }
}
